### ISSUE TITLE
Contribution ERROR: Source location must be an object

### ISSUE THREAD

**Issue by AE49** [clearlydefined/website#779] opened 2019-07-09 16:55 UTC
I need to curate these NPM packages for a NOTICE. I'm receiving the following error when I hit contribute for the Clearly Defined curation:

**Contribution ERROR: Source location must be an object**

o	npm/npmjs/-/amdefine/0.1.0
o	npm/npmjs/-/base64id/0.1.0
o	npm/npmjs/-/benchmark/1.0.0
o	npm/npmjs/-/engine.io-client/1.5.4
o	npm/npmjs/-/engine.io/1.5.1
o	npm/npmjs/-/ms/0.6.2

**Comment by fossygirl** [comment] 2019-07-09 17:00
@ignacionr @storrisi

**Comment by ignacionr** [comment] 2019-07-09 17:06
Could you share steps to reproduce? Does it happen if you take only one package (let's say npm/npmjs/-/amdefine/0.1.0) and make one curation? (The field being edited would also help if you can share it, as well as the value that you're changing it to.)

**Comment by ariel11** [comment] 2019-07-09 17:50
@AE49 - I have *no idea* why this would work, but I have received this error too and gone back and tried curating again selecting a different option from the first drop-down menu on the Contribute window and had it go through.

**Comment by AE49** [comment] 2019-07-09 18:15
@ignacionr Hi, I'm doing the same steps each time regardless of package type, and I am curating each of these components listed in my issue individually. This error is showing today for NPM packages only. Steps: I select "Incomplete" in the first drop down, add Declared License in the title, Add MIT for subject and a link for resolution. When I hit "Contribute" the error message shows up.

**Comment by AE49** [comment] 2019-07-09 18:19
@ariel11 thanks. I have experienced the same - where I might get an error one day or I can't hit the contribute button and if I try again another day the issue is no longer there. I have had this particular error before. If they can get to the cause perhaps they can fix instead of a workaround.

**Comment by ignacionr** [comment] 2019-07-10 01:23
@AE49 maybe we can set up a Discord screen share session so you can show me how this comes up? I have done some testing and couldn't reproduce the issue you see. Your help is much appreciated.

**Comment by AE49** [comment] 2019-07-10 16:04
@ignacionr Sure, when's good for you? I'm free at 9:30 or after 11.

**Comment by ariel11** [comment] 2019-07-10 16:39
@ignacionr and @AE49 - I just took a look and could submit successfully if I just searched for the component in the Workspace and did not dig into the definition (https://github.com/clearlydefined/curated-data/pull/2202 and https://github.com/clearlydefined/curated-data/pull/2201.  However, if I clicked on the magnifying glass and then tried to contribute, I got the source error.

**Comment by ignacionr** [comment] 2019-07-11 01:24
@ariel11 is this repeatable every time (have you been able to reproduce the issue more than once)?
It’s very interesting.

**Comment by AE49** [comment] 2019-07-11 12:58
@ignacionr @ariel11 I was able to curate the remaining components today, with exception of one. I didn't do anything different except select "Missing" today instead of "Incomplete". This component is the last one showing no source object and will not allow me to contribute - https://clearlydefined.io/definitions/npm/npmjs/-/ms/0.6.2.

**Comment by ignacionr** [comment] 2019-07-11 15:11
@ariel11 and @AE49 is this still a problem? I went on and created https://github.com/clearlydefined/curated-data/pull/2209 from the website, but I'm not sure this is exactly what you wanted, and there weren't any noticeable hiccups; sorry I wasn't able to reproduce the issue.

**Comment by ignacionr** [comment] 2019-07-23 16:58
This was resolved by using a tool. Please re-open if necessary.

**Closed by ignacionr** 2019-07-23 16:58 UTC
Labels: bug

**Comment by AE49** [comment] 2019-07-24 23:35
@fossygirl @ignacionr @geneh I'm getting the same "Contribution ERROR: Source location must be an object" for the following components:

•	git/github/antaris/razorengine/4399028120f3c570fc8049fba9c055ac9be81468
•	git/github/automattic/cli-table/e35ccee7341e8574839df751a8aa10acd5a82a5b
•	git/github/azure/azure-docker-extension/0dd2f199467db78e91d28c30d8595d1bcaf776de
•	git/github/azure/azure-docker-extension/2727dce2785d0a3cdca692387b0acee36b908351
•	git/github/azure/azure-docker-extension/8c5236a9ab19fabd2fb77c606b419caad376f6d7
•	git/github/azure/azure-linux-extensions/3093bb8af7f652e59486c99ba3814d1db3e88b66
•	git/github/azure/azure-linux-extensions/9c96c34f085c0212430330ff11f1c68170403697
•	git/github/azure/azure-linux-extensions/fa375841072581690bbd23a929db1aa453973d
