### ISSUE TITLE
Curation UI behaves confusingly and does not remove old license

### ISSUE THREAD

**Issue by maxhbr** [clearlydefined/website#678] opened 2019-04-25 13:36 UTC
I am looking on [git/github/lz4/lz4/dfed9fa1d77f0434306d377c4da1f7191d3ba08](https://clearlydefined.io/definitions/git/github/lz4/lz4/dfed9fa1d77f0434306d377c4da1f7191d3ba08)a at the file `lib/dll/example/Makefile`. The file has the old SPDX ID `GPL-2.0+` as license. If I use pencil-icon or the eye-icon to modify the license to `GPL-2.0-or-later` the UI always displays `GPL-2.0+ AND GPL-2.0-or-later` afterwards.

## Screenshots:
before the change:
![2019-04-25_15:31:15](https://user-images.githubusercontent.com/1187050/56739755-c70c1780-676f-11e9-893b-34fec69fb431.png)
after the change:
![2019-04-25_15:32:02](https://user-images.githubusercontent.com/1187050/56739764-ce332580-676f-11e9-8277-387d066f2590.png)

**Comment by storrisi** [comment] 2019-04-25 13:43
Looks like a service issue, i've reproduced the problem with another definition.

This is the PATCH details sent to the preview endpoint:

`{"files":[{"path":"Makefile","license":"0BSD","attributions":["Copyright (c) Yann Collet 2011-2016"]}]}`

and this is the response of the related file:

`{"path":"Makefile","license":"0BSD AND BSD-2-Clause","attributions":["Copyright (c) Yann Collet 2011-2016"],"hashes":{"sha1":"e352eb782a0948c9f1154462f903f88dcbd17abb"}}`

**Comment by storrisi** [comment] 2019-04-26 16:55
@dabutvin did you had the chance to look at this? Should we move this issue to the service repo?

**Comment by storrisi** [comment] 2019-05-06 14:39
@dabutvin i think this should be moved to the service. We can then take care of this and see why it has this strange behavior.

**Comment by storrisi** [comment] 2019-05-14 15:51
This is related to https://github.com/clearlydefined/service/issues/526

**Comment by storrisi** [comment] 2019-05-31 13:37
Since this has been fixed by clearlydefined/service#526 , we can close this one.

**Closed by storrisi** 2019-05-31 13:37 UTC
Labels: bug
