### ISSUE TITLE
Browse: Sort by score should use combined effective score

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#495] opened 2019-02-25 18:03 UTC
[changed direction described here]
The /browse page enables people to sort by licensed and described score. We are moving to a model where the pages show just one score, the combined effective score. That will simplify the user model. From the curator point of view that's fine as they should look for things with low score and curate. We'll need to do something else to guide component producers to their components that have low scores.

**Comment by storrisi** [comment] 2019-03-07 11:04
To do that, we need to address some changes on the service, in order to do the right queries on mongoDb.

I've addressed the required work on a specific issue: https://github.com/clearlydefined/service/issues/436

**Comment by storrisi** [comment] 2019-03-07 14:44
Going through the implementation, looks like that filtering the list directly in the UI will not produce the expected behavior.
Since the result of the Browse page is a paginated list, we should be able only to filter the received data, and not the entire collection that the server has.

Probably we should find a more consistent way to do that on the service.

**Comment by jeffmcaffer** [comment] 2019-03-07 16:31
On the /browse page, all sorting and filtering must be done server-side as we are talking about the global list of definitions. So here we should be adding a query parameter and the right query construct in the service.

**Comment by jeffmcaffer** [comment] 2019-03-07 16:38
Reviewing this issue I think something has changed in the meantime. That is, the site now (soon) only shows one score, the effective score combined across all the dimensions (described and licensed). I'm going to update the title and description to better capture the current state and direction.

**Comment by storrisi** [comment] 2019-03-07 16:45
Thanks @jeffmcaffer .
Since we are going to filter for a value that actually doesn't exists on a definition, but it's computed on the client, should we think on returning that combined value from the service, something like we've done for the urls of a definition?

**Comment by storrisi** [comment] 2019-03-08 09:54
The answer to my last question has been addressed in the implementation of https://github.com/clearlydefined/service/pull/439 

Given that, scores coming from the server will be used instead of computing those in the UI.

**Closed** 2019-03-08 17:29 UTC
