### ISSUE TITLE
Make source location clickable in popup

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#418] opened 2019-01-24 21:55 UTC
Source link in popup for curating source location should be clickable.

**Comment by jeffmcaffer** [comment] 2019-01-27 20:17
There are actually two problems here.

1) the link for the source location is buried in a dialog meaning that users need to open the dialog click on the link and then close the dialog

2) the link actually navigates in place rather than opening a new tab. That means that any work in progress is lost.

We can fix the second one easily. The first will take some UI design to decide on the right behavior and look.

**Comment by jeffmcaffer** [comment] 2019-01-27 20:46
dupe of #347

**Closed by jeffmcaffer** 2019-01-27 20:46 UTC
