### ISSUE TITLE
Address layout of component list panel

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/website#74] opened 2018-03-01 19:24 UTC
Narrow your browser a bit:

![image](https://user-images.githubusercontent.com/299129/36864803-8d0d44d2-1d42-11e8-961c-8a559583a06b.png)

At first glance it seems like the infinite list stuff seems to be adding fixed heights and using absolute positioning which doesn't play well with bootstrap's responsive css.

**Comment by storrisi** [comment] 2019-02-19 17:24
The problem is not evident as it was when the issue was opened, but actually there is still some visualization issues when reducing the browser size.
Maybe we should address all of these issues in relationship to #95

**Comment by dabutvin** [comment] 2019-02-19 20:10
@storrisi I did a quick mockup of the panel in a mobile view.

![image](https://user-images.githubusercontent.com/5168796/53043221-dbb0f400-343c-11e9-85e7-7ed674a14e3a.png)

And then when you click the magnifying glass a mobile view like this:

![image](https://user-images.githubusercontent.com/5168796/53044242-511dc400-343f-11e9-88d4-c9765859e849.png)
![image](https://user-images.githubusercontent.com/5168796/53044246-5418b480-343f-11e9-873c-6ca1610ce9ed.png)
![image](https://user-images.githubusercontent.com/5168796/53044252-567b0e80-343f-11e9-9ed8-0ed9095593b9.png)


Let me know what you think?

**Comment by storrisi** [comment] 2019-02-19 21:09
Thanks @dabutvin , your work is really helpful.

In your mockup some of the buttons in the definitions list are missing, and in the details view some of the sections could be difficult to be used in a mobile environment (like the FileList).
We should try to maintain as many functionalities as possible and at the same make them usable on a mobile screen.
BTW i think that #95 can be a better place to have a discussion about the responsive topic.

Considering only the Definitions list which is the subject of this issue, i suggest to have an hamburger icon button, which contains all the buttons for each element.

Thoughts?

**Comment by dabutvin** [comment] 2019-02-19 21:32
Thanks for checking it out!
I actually removed those items intentionally, thinking that we should guide the user into the fullDetailView on mobile if they want to take any of those actions. 
Maybe we can add those buttons to the fullDetailView if they are needed?

**Comment by storrisi** [comment] 2019-02-19 21:38
Good point, but not all the buttons can be addressed in the Detail view.
Some of them are related to operations that could add or change the set of components that the user is using.
It means that, if those were used in the detail view, the user should open and close the modal to see if anything has happened.

**Comment by dabutvin** [comment] 2019-02-19 21:40
ahh right, yeah you are right. Let's not add them anywhere else and just hide them for now.
Maybe we can show them as space allows if that doesn't get too complicated

**Comment by storrisi** [comment] 2019-02-19 21:43
We will share a proposal of the behavior asap, and then we would make all the necessary discussions on top of that

**Comment by mynameistechno** [comment] 2019-02-20 00:39
> Let me know what you think?

👏

**Comment by mynameistechno** [comment] 2019-02-20 00:50
The original issue I opened was more related to issues with the desktop UI (looks like much of it has been addressed 👍). 

I'm not sure how much of the desktop functionality needs to be exposed via a mobile interface. I think it would be reasonable to hide some of the more advanced functionality if it's hard to fit on a small screen, or if it doesn't make sense on mobile. E.g. will people be curating via their phones or just performing a quick search?

**Comment by storrisi** [comment] 2019-02-21 10:59
> I'm not sure how much of the desktop functionality needs to be exposed via a mobile interface. I think it would be reasonable to hide some of the more advanced functionality if it's hard to fit on a small screen, or if it doesn't make sense on mobile. E.g. will people be curating via their phones or just performing a quick search? 🤷‍♂️

Thanks @mynameistechno , that is pretty much the same thing i'm currently thinking.
We could involve @fossygirl in the discussion, since perhaps she have some thoughts about the big picture should be

**Closed** 2019-03-22 17:56 UTC
