### ISSUE TITLE
/harvest UX permissioned and may not work 

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#653] opened 2019-04-10 07:55 UTC
There is still a permission check on exposing the /harvest UX. even when signed in, actually trying to harvest something does not work. you can pick a component name but then the screen goes blank. I've not had a chance to investigate

**Comment by storrisi** [comment] 2019-04-10 08:20
Looks like that the same problem is already solved in dev, maybe we only need to make a release to prod?

**Comment by storrisi** [comment] 2019-04-10 08:24
I've investigated further more, the problem is related to the title and alt property of the provider image, this has been fixed in https://github.com/clearlydefined/website/pull/609 and needs to be released to prod.
The last release on prod was 23 days ago and this fix is from 21 days ago.

**Comment by jeffmcaffer** [comment] 2019-04-10 08:41
Thanks @Simo, looks like we need to push to prod. 

@dabutvin, can you drive this today if things are looking good. Would love to be demoing the latest.

**Comment by storrisi** [comment] 2019-04-10 20:54
Now that all the fixes have been release to prod, i don't see the problem anymore, we can close this.

**Comment by dabutvin** [comment] 2019-04-10 21:00
👍 👍 👍

**Closed by dabutvin** 2019-04-10 21:00 UTC
Labels: bug
