### ISSUE TITLE
Not able to edit file-level license

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#955] opened 2022-03-01 16:04 UTC
The edit button does nothing when trying to edit the license info for a file. Also, clicking on the license field does nothing.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/5489711/156204040-c59ce117-4cc4-40f8-be75-ef5173ea54e2.png">

**Comment by capfei** [comment] 2023-01-09 20:58
Can confirm that I am able to do file-level edits (haven't submitted a PR, though) and experiencing the same issue with the radio buttons.

**Comment by qtomlinson** [comment] 2023-01-10 00:12
Commit `https://github.com/clearlydefined/website/pull/977/commits/5c0a7215567b1506395c8b375edb680e19f62f65` reused LicensePicker for license editing.  It seems that LicensePicker needs some work as well.

**Comment by qtomlinson** [comment] 2023-01-10 17:17
@capfei @bduranc The improvement needed in LicensePicker is more general and not limited to "file-level license" editing. Editing license in the "Described and Licensed" of the definition page shows the same dialogue and needs the same improvement.  The original use case of "Not able to edit file-level license" is now supported.  The improvement LicensePicker  is better documented in a separate issue, so that all the test cases (file-level and declared license) can be addressed.

![image](https://user-images.githubusercontent.com/92891533/211618599-bf5c3e74-fd14-4f97-bc9a-832f897079a6.png)

**Comment by bduranc** [comment] 2023-01-10 19:03
Alright, I will open new issue to discuss the usability of this dialog box.

It is worth mentioning that in the old UI, this function did work much better because none of these issues existed.

**Comment by bduranc** [comment] 2023-01-13 19:53
I confirmed I was able to submit this curation PR: https://github.com/clearlydefined/curated-data/pull/23164

I created issue #1013 addresses the larger problemswith the LicensePicker component itself. But for the original scope of this issue, it looks like the problem is fixed.

@capfei do we want to close this?

**Closed** 2023-01-13 23:00 UTC
