### ISSUE TITLE
"Download component" button appears to cause trouble for Maven definitions; Update Maven URLs

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#864] opened 2020-01-28 22:00 UTC
Issue Type: Bug
Issue Severity: **Low**
Issue Description:

The blue "Download component" button that appears on the right-hand side of the _Files_ pane does not appear to point to a valid place on Maven anymore. 

When you click on the button, a) it will ask you to use HTTPS (501). 

![image](https://user-images.githubusercontent.com/31491646/73308933-22bf7180-41d6-11ea-9c46-6c5ee0b5b3e8.png)

b) once you change the prefix to "https://", you're presented with a 403 telling you must use "repo1.maven.org". In most cases I've tried, the JAR file will download once you change to _repo1_.

![image](https://user-images.githubusercontent.com/31491646/73308949-2a7f1600-41d6-11ea-8186-e20a5b97af02.png)

Here's just one of many an examples I tried with: https://clearlydefined.io/definitions/maven/mavencentral/com.amazonaws/aws-java-sdk-cognitoidentity/1.11.699

Perhaps the URLs need to be updated?

Thanks.

**Comment by ariel11** [comment] 2020-11-02 21:31
See also: https://github.com/clearlydefined/service/issues/755,  https://github.com/clearlydefined/service/issues/707

**Comment by nellshamrell** [comment] 2021-01-05 18:50
Confirmed that this is still an issue - and it appears to be on the service side. Closing this since https://github.com/clearlydefined/service/issues/755,  https://github.com/clearlydefined/service/issues/707 are open on the service repo.

**Closed by nellshamrell** 2021-01-05 18:50 UTC
Labels: bug
