### ISSUE TITLE
Full details page fails to load if curations or suggestions fail

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#535] opened 2019-03-03 04:12 UTC
We had a case where /curation and /suggestions APIs were failing with 500s. That seemed to cause the whole Full details page to fail to load. Rather, the page should load and the curations or suggestions should fill in lazily (or not)

**Comment by storrisi** [comment] 2019-03-12 16:05
I've tried locally forcing the routes /curation and /suggestions to return a 500 error, but i'm unable to reproduce the error.
Seems that everything is working fine right now.

Actually those calls shouldn't affect the load of the page.

**Comment by storrisi** [comment] 2019-03-15 15:27
I'm still not able to reproduce the problem. 
Maybe there was also a problem while loading the definition as well?

**Comment by storrisi** [comment] 2019-05-02 16:20
@jeffmcaffer is this problem happened again? I was not able to reproduce it in order to solve it.

**Comment by storrisi** [comment] 2019-08-12 17:12
I'm going to close this for now since looks that the problem didn't happen again. We can even open it again with some supporting information about how to reproduce it.

**Closed by storrisi** 2019-08-12 17:12 UTC
