### ISSUE TITLE
add sorting on browse

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#59] opened 2018-02-25 05:37 UTC
users should be able to sort the components they have found while browsing. For example, sort by licenses, CD score, age, provider/type, group source with package, ...

**Comment by fossygirl** [comment] 2018-06-18 21:05
https://github.com/clearlydefined/website/issues/126 may be a duplicate of this. We can close one.

**Comment by fossygirl** [comment] 2018-06-18 21:12
Closing as a duplicate of #126

**Closed by fossygirl** 2018-06-18 21:12 UTC
Labels: good first issue, help wanted
