### ISSUE TITLE
ERROR: Source Location must be an object.

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/website#346] opened 2018-10-26 19:53 UTC
I received the above ERROR when I tried to contribute about 25 "declared licenses" at once.

**Comment by fossygirl** [comment] 2018-12-18 17:57
@ariel11 Can you confirm this is still an issue for you? If not I'll close this and we can reopen if you have the trouble again.

**Comment by ariel11** [comment] 2018-12-18 19:09
@fossygirl - OK to close.  We will see if it happens again.

**Comment by AE49** [comment] 2019-06-05 19:42
I received the above error when I tried to contribute the following components:

https://clearlydefined.io/definitions/git/github/abrkn/semaphore.js/4b7471c5efc348b3279621e58e0b47b55ac60040

https://clearlydefined.io/definitions/git/github/go-logfmt/logfmt/d4327190ff838312623b09bfeb50d7c93c8d9c1d

https://clearlydefined.io/definitions/git/github/go-stack/stack/100eb0c0a9c5b306ca2fb4f165df21d80ada4b82

It is likely there will be more components with the same issue in a big patch to curate for Azure Stack.

**Comment by fossygirl** [comment] 2019-06-05 19:44
@geneh

**Comment by storrisi** [comment] 2019-06-06 15:57
@AE49 may i ask you what was the content of the contribution? I would like to reproduce it on our dev environment. Thanks!

**Comment by AE49** [comment] 2019-06-06 16:03
@storrisi Hi, I was adding MIT as the Declared License, and when I hit contribute I get the error.

**Comment by storrisi** [comment] 2019-06-06 16:07
@AE49 thanks for clarifying it. I will check.

**Comment by storrisi** [comment] 2019-06-11 15:40
I'm sorry, but i'm still unable to reproduce this problem.
I've tried different approaches:
- from the workspace list
- from the detail page

The results is the same: every time i change something and hit Contribute, the Contribute Modal prompts correctly.

Maybe a screenshot when the error happens would help.

**Comment by AE49** [comment] 2019-06-11 15:45
@storrisi thanks for checking. The first one is now showing as curated and the other two as pending so perhaps there's no issue to resolve. We can close this for now.

**Closed** 2019-06-11 15:46 UTC
Labels: bug

**Comment by ariel11** [comment] 2019-07-26 21:16
This is still happening - 
![image](https://user-images.githubusercontent.com/17935946/61981921-f66d3300-afaf-11e9-9bf5-5dee2194d3dc.png)

**Comment by fossygirl** [comment] 2019-07-26 21:17
This is being tracked on https://github.com/clearlydefined/website/issues/792.
