### ISSUE TITLE
Adding a lot of versions to a definition curation hides the OK/Cancel buttons

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#512] opened 2019-02-26 23:07 UTC
If I add a bunch of versions to a definition I'm curating the OK/Cancel options get hidden. Clicking away from the screen doesn't save my work.
![screen shot 2019-02-26 at 3 05 34 pm 2](https://user-images.githubusercontent.com/17101092/53453138-3798f100-39d8-11e9-91cb-0c6a2e3d6e00.png)

**Comment by gianpaj** [comment] 2019-02-27 12:07
Hi @fossygirl ,

I believe the issue is the fact that the modal was closing when there are versions added to the input field.

Would this behaviour be better (see GIF below)?:
- When clicking outside the modal (dark backdrop) don't close the Modal if there are any changes made (versions added in the input field)
- Close the modal if the input field is empty

![versions modal](https://user-images.githubusercontent.com/899175/53489097-e7359800-3a98-11e9-90b3-d9662524b8f8.gif)

**Comment by fossygirl** [comment] 2019-02-27 15:09
Sure, this is a fine change.

**Closed** 2019-02-28 18:06 UTC
Labels: bug
