### ISSUE TITLE
Add drag and drop for component searching

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#41] opened 2018-01-29 03:48 UTC
rather than entering selections one by one, users should be able to drag a file listing components and drop it on the search input text box.

The file could be
* ORT package dependencies file
* package.json, project.assets or any other fully resolve package manager dependency file
* CSV
* one entry per line
* JSON array

Where each entry might be 
* various forms of canonical web URLs
* CD component specs

**Comment by fossygirl** [comment] 2018-02-13 00:30
We are considering this a stretch goal for our OSLS demo.

**Comment by fossygirl** [comment] 2018-03-02 21:25
Removing OSLS milestone, we decided we won't get to this for next week.

**Comment by fossygirl** [comment] 2018-06-18 21:06
https://github.com/clearlydefined/website/issues/124 may be a duplicate of this. I will merge.

**Comment by fossygirl** [comment] 2018-06-18 21:07
Closing as a duplicate of #124

**Closed by fossygirl** 2018-06-18 21:07 UTC
